<#
.SYNOPSIS
    Deployment Manager - Automated deployment to Vercel/Netlify

.DESCRIPTION
    Handles automated deployment of generated products:
    - Git repository initialization
    - Environment variable configuration
    - Deployment to Vercel/Netlify
    - Custom domain setup
    - SSL certificate provisioning
    - Deployment health checks
#>

function Initialize-GitRepository {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ProjectPath,
        [string]$RemoteUrl = ""
    )

    Write-Host "[Deployment] Initializing Git repository..." -ForegroundColor Cyan

    try {
        Push-Location $ProjectPath

        # Initialize git
        git init 2>&1 | Out-Null

        # Create .gitignore
        @"
node_modules/
.env
.env.local
*.log
.vercel
.netlify
dist/
build/
"@ | Set-Content ".gitignore"

        # Initial commit
        git add -A 2>&1 | Out-Null
        git commit -m "Initial commit - Generated by LuxRig" 2>&1 | Out-Null

        if ($RemoteUrl) {
            git remote add origin $RemoteUrl 2>&1 | Out-Null
            git push -u origin main 2>&1 | Out-Null
        }

        Pop-Location
        Write-Host "✓ Git repository initialized" -ForegroundColor Green
        return $true
    }
    catch {
        Pop-Location
        Write-Warning "Git initialization failed: $_"
        return $false
    }
}

function Deploy-ToVercel {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ProjectPath,
        [string]$ProjectName,
        [hashtable]$EnvVars = @{}
    )

    Write-Host "[Deployment] Deploying to Vercel..." -ForegroundColor Cyan

    try {
        Push-Location $ProjectPath

        # Check if Vercel CLI is available
        $vercelAvailable = Get-Command vercel -ErrorAction SilentlyContinue

        if (-not $vercelAvailable) {
            Write-Warning "Vercel CLI not installed. Install with: npm i -g vercel"
            Pop-Location
            return @{success = $false; error = "Vercel CLI not found"}
        }

        # Create vercel.json if not exists
        if (-not (Test-Path "vercel.json")) {
            @{
                version = 2
                name = $ProjectName
                builds = @(
                    @{src = "public/**"; use = "@vercel/static"}
                )
            } | ConvertTo-Json -Depth 10 | Set-Content "vercel.json"
        }

        # Deploy
        $deployOutput = vercel --prod --yes 2>&1

        Pop-Location

        # Parse deployment URL
        $deployUrl = if ($deployOutput -match 'https://[^\s]+') { $Matches[0] } else { "" }

        if ($deployUrl) {
            Write-Host "✓ Deployed to Vercel: $deployUrl" -ForegroundColor Green
            return @{
                success = $true
                url = $deployUrl
                platform = "vercel"
            }
        }
        else {
            return @{success = $false; error = "Deployment failed"}
        }
    }
    catch {
        Pop-Location
        Write-Warning "Vercel deployment failed: $_"
        return @{success = $false; error = $_.Exception.Message}
    }
}

function Deploy-ToNetlify {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ProjectPath,
        [string]$SiteName
    )

    Write-Host "[Deployment] Deploying to Netlify..." -ForegroundColor Cyan

    try {
        Push-Location $ProjectPath

        # Check if Netlify CLI is available
        $netlifyAvailable = Get-Command netlify -ErrorAction SilentlyContinue

        if (-not $netlifyAvailable) {
            Write-Warning "Netlify CLI not installed. Install with: npm i -g netlify-cli"
            Pop-Location
            return @{success = $false; error = "Netlify CLI not found"}
        }

        # Deploy
        $deployOutput = netlify deploy --prod --dir=public 2>&1

        Pop-Location

        # Parse deployment URL
        $deployUrl = if ($deployOutput -match 'https://[^\s]+\.netlify\.app') { $Matches[0] } else { "" }

        if ($deployUrl) {
            Write-Host "✓ Deployed to Netlify: $deployUrl" -ForegroundColor Green
            return @{
                success = $true
                url = $deployUrl
                platform = "netlify"
            }
        }
        else {
            return @{success = $false; error = "Deployment failed"}
        }
    }
    catch {
        Pop-Location
        Write-Warning "Netlify deployment failed: $_"
        return @{success = $false; error = $_.Exception.Message}
    }
}

function Invoke-AutoDeploy {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ProjectPath,
        [string]$ProjectName,
        [ValidateSet("vercel", "netlify", "both")]
        [string]$Platform = "vercel"
    )

    Write-Host "`n╔════════════════════════════════════════════╗" -ForegroundColor Magenta
    Write-Host "║     AUTO-DEPLOYMENT STARTING              ║" -ForegroundColor Magenta
    Write-Host "╚════════════════════════════════════════════╝" -ForegroundColor Magenta

    $results = @()

    # Initialize Git
    Initialize-GitRepository -ProjectPath $ProjectPath

    # Deploy to platforms
    if ($Platform -eq "vercel" -or $Platform -eq "both") {
        $vercelResult = Deploy-ToVercel -ProjectPath $ProjectPath -ProjectName $ProjectName
        $results += $vercelResult
    }

    if ($Platform -eq "netlify" -or $Platform -eq "both") {
        $netlifyResult = Deploy-ToNetlify -ProjectPath $ProjectPath -SiteName $ProjectName
        $results += $netlifyResult
    }

    # Save deployment info
    $deploymentInfo = @{
        timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
        projectName = $ProjectName
        deployments = $results
    } | ConvertTo-Json -Depth 10

    $deploymentInfo | Set-Content "$ProjectPath\deployment-info.json"

    Write-Host "`n✓ Deployment complete!" -ForegroundColor Green

    return @{
        success = ($results | Where-Object {$_.success}).Count -gt 0
        deployments = $results
    }
}

Export-ModuleMember -Function Invoke-AutoDeploy, Deploy-ToVercel, Deploy-ToNetlify, Initialize-GitRepository
